### ISSUE TITLE
Factory should probably ensure that class is a Fixture

### ISSUE THREAD

**Issue by sbellware** [test-bench/test-bench-fixture#1]
Re: https://github.com/test-bench/test-bench-fixture/blob/master/lib/test_bench/fixture/fixture.rb#L25

Seems like it should check that the class `is_?(TestBench::Fixture)`, and that the error message should not just say "Must be given a class", but, "Must be given a class that implements TestBench::Fixture".

**Comment by ntl** [comment]
This is done in the latest release.
