### ISSUE TITLE
The output from context and test blocks inside a block-form assert should always print 

### ISSUE THREAD

**Issue by sbellware** [test-bench/test-bench-fixture#5]
Rather than just print when there's an error.

Context and test are fundamental test structure. They should always be output, rather than be considered variable.

Comments, though, are a different matter. Comments inside test blocks are variable. However, those comments might best be referred to as something other than "comment". Maybe `verbose` should be used for those. Especially if verbose is to always be printed when there's a failure in a fixture per #3.

**Comment by ntl** [comment]
This is no longer an issue in the latest release, since we now have `detail` (and block-form assertions are gone anyways)
